import { EnumRole, EnumGender } from '@/types/enum';

export const dummyTeacherData = [
  {
    lecturer: null,
    id: 1,
    username: '21089141',
    avatar: 'avatar1.jpg',
    name: 'Nguyễn Văn A',
    email: 'teacher1@example.com',
    phoneNumber: '0123456789',
    gender: EnumGender.MALE,
    role: EnumRole.LECTURER,
    majors: {
      id: 123,
    },
    degree: 'MASTERS',
    isAdmin: false,
    isActive: false
  },
  {
    lecturer: null,
    id: 2,
    username: 'teacher2',
    avatar: 'avatar2.jpg',
    name: 'Trần Thị B',
    email: 'teacher2@example.com',
    phoneNumber: '0987654321',
    gender: EnumGender.FEMALE,
    role: EnumRole.LECTURER,
    majors: {
      id: 456,
    },
    degree: 'DOCTER',
    isAdmin: false,
    isActive: true,
  },
  {
    lecturer: null,
    id: 3,
    username: 'teacher3',
    avatar: 'avatar3.jpg',
    name: 'Lê Văn C',
    email: 'teacher3@example.com',
    phoneNumber: '0369852147',
    gender: EnumGender.FEMALE,
    role: EnumRole.LECTURER,
    majors: {
      id: 789,
    },
    degree: 'MASTERS',
    isAdmin: false,
    isActive: false,
  },
  {
    lecturer: null,
    id: 4,
    username: 'teacher4',
    avatar: 'avatar4.jpg',
    name: 'Phạm Thị D',
    email: 'teacher4@example.com',
    phoneNumber: '0912345678',
    gender: EnumGender.FEMALE,
    role: EnumRole.LECTURER,
    majors: {
      id: 1011,
    },
    degree: 'DOCTER',
    isAdmin: false,
    isActive: true,
  },
  {
    lecturer: null,
    id: 5,
    username: 'teacher5',
    avatar: 'avatar5.jpg',
    name: 'Hoàng Văn E',
    email: 'teacher5@example.com',
    phoneNumber: '0975321648',
    gender: EnumGender.MALE,
    role: EnumRole.LECTURER,
    majors: {
      id: 1213,
    },
    degree: 'MASTERS',
    isAdmin: false,
    isActive: true,
  },
];
