export const dummyTopics = [
  {
    id: 1,
    comment: 'Nhận xét về đề tài 1',
    description: 'Mô tả đề tài 1',
    lecturer: {
      id: 1,
      name: 'Nguyễn Văn A',
      email: 'nguyenvana@example.com',
    },
    name: 'Phát triển ứng dụng web',
    note: 'Ghi chú về đề tài 1',
    quantityGroupMax: 5,
    requireInput: 'Yêu cầu input cho đề tài 1',
    standradOutput: 'Kết quả mong đợi cho đề tài 1',
    status: 'ACCEPT',
    target: 'Mục tiêu của đề tài 1',
    term: { id: 1 },
    totalGroupChoose: 3,
    level: 'HIGH',
  },
  {
    id: 2,
    comment: 'Nhận xét về đề tài 2',
    description: 'Mô tả đề tài 2',
    lecturer: {
      id: 1,
      name: 'Nguyễn Văn A',
      email: 'nguyenvana@example.com',
    },
    name: 'Xây dựng ứng dụng di động',
    note: 'Ghi chú về đề tài 2',
    quantityGroupMax: 4,
    requireInput: 'Yêu cầu input cho đề tài 2',
    standradOutput: 'Kết quả mong đợi cho đề tài 2',
    status: 'PENDING',
    target: 'Mục tiêu của đề tài 2',
    term: { id: 1 },
    totalGroupChoose: 2,
    level: 'HIGH',
  },
  {
    id: 3,
    comment: 'Nhận xét về đề tài 3',
    description: 'Mô tả đề tài 3',
    lecturer: {
      id: 2,
      name: 'Trần Thị B',
      email: 'tranthib@example.com',
    },
    name: 'Xử lý dữ liệu lớn',
    note: 'Ghi chú về đề tài 3',
    quantityGroupMax: 6,
    requireInput: 'Yêu cầu input cho đề tài 3',
    standradOutput: 'Kết quả mong đợi cho đề tài 3',
    status: 'REFUSE',
    target: 'Mục tiêu của đề tài 3',
    term: { id: 2 },
    totalGroupChoose: 1,
    level: 'MEDIUM',
  },
];
